### PR TITLE
Fix Balancer Post Hooks

### PR DESCRIPTION
**Pull request by hedgehog-jacek**
Brief comments on the purpose of your changes:

 - Fixed the post hooks for Balancer queries so that there is distinction between Balancer v1 and v2 queries.

**For Dune Engine V2**

I've checked that:

### General checks:
* [x] I tested the query on dune.com after compiling the model with dbt compile (compiled queries are written to the target directory)
* [x] I used "refs" to reference other models in this repo and "sources" to reference raw or decoded tables 
* [x] if adding a new model, I added a test
* [x] the filename is unique and ends with .sql
* [x] each sql file is a select statement and has only one view, table or function defined  
* [x] column names are `lowercase_snake_cased`
* [x] if adding a new model, I edited the dbt project YAML file with new directory path for both models and seeds (if applicable)
* [x] if wanting to expose a model in the UI (Dune data explorer), I added a post-hook in the JINJA config to add metadata (blockchains, sector/project, name and contributor Dune usernames)

### Pricing checks:
* [ ] ~~`coin_id` represents the ID of the coin on coinpaprika.com~~
* [ ] ~~all the coins are active on coinpaprika.com (please remove inactive ones)~~

### Join logic:
* [ ] ~~if joining to base table (i.e. ethereum transactions or traces), I looked to make it an inner join if possible~~

### Incremental logic:
* [ ] ~~I used is_incremental & not is_incremental jinja block filters on both base tables and decoded tables~~
  * [ ] ~~where block_time >= date_trunc("day", now() - interval '1 week')~~
* [ ] ~~if joining to base table (i.e. ethereum transactions or traces), I applied join condition where block_time >= date_trunc("day", now() - interval '1 week')~~
* [ ] ~~if joining to prices view, I applied join condition where minute >= date_trunc("day", now() - interval '1 week')~~

### CODE REVIEW

**Comment by mendesfabio** [comment]
@hedgehog-jacek shouldn't we move these files to `balancer_v1` and `balancer_v2` folders as well?

**Comment by Stefenon** [comment]
> @hedgehog-jacek shouldn't we move these files to `balancer_v1` and `balancer_v2` folders as well?

I think the changes would work without doing that, but it might be a good idea for organization purposes. In this case, would we need to create schema files for v1 and v2 as well?

**Comment by mendesfabio** [comment]
yeah, I now understand that folder structure doesn't matter on Spellbook but only these configs. I'm actually fine opening this PR as it is because other projects that have multiple versions have all queries in the same folder e.g. [Uniswap](https://github.com/duneanalytics/spellbook/tree/main/models/uniswap/ethereum). If we find it hard to manage in the future, we can always change it.

**Comment by mendesfabio** [comment]
@hedgehog-jacek can we open this PR to Dune?

**Review by mendesfabio — APPROVED** [review]
@hedgehog-jacek please open this PR on Dune's Spellbok

**Comment by hedgehog-jacek** [comment]
I am closing this PR and creating a new one to the Dune repo.

**Pull request closed without merging**
